<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <soap:Body>
    <wsConsultaEstudiantesResponse xmlns="http://tempuri.org/">
      <wsConsultaEstudiantesResult>
        <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
          <xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:UseCurrentLocale="true">
            <xs:complexType>
              <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="Estudiantes">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="NOMBRES" type="xs:string" minOccurs="0" />
                      <xs:element name="APELLIDOS" type="xs:string" minOccurs="0" />
                      <xs:element name="COD_ESTUDIANTE" type="xs:string" minOccurs="0" />
                      <xs:element name="EMAIL" type="xs:string" minOccurs="0" />
                      <xs:element name="PARALELO" type="xs:string" minOccurs="0" />
                      <xs:element name="COD_MATERIA_ACAD" type="xs:string" minOccurs="0" />
                      <xs:element name="NOMBRE" type="xs:string" minOccurs="0" />
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:choice>
            </xs:complexType>
          </xs:element>
        </xs:schema>
        <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
          <NewDataSet xmlns="">
            <Estudiantes diffgr:id="Estudiantes1" msdata:rowOrder="0">
              <NOMBRES>STEVEN SEBASTIAN</NOMBRES>
              <APELLIDOS>MACIAS QUEZADA</APELLIDOS>
              <COD_ESTUDIANTE>201121507</COD_ESTUDIANTE>
              <EMAIL>stsemaci@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes2" msdata:rowOrder="1">
              <NOMBRES>JOSELINE YAJAIRA</NOMBRES>
              <APELLIDOS>PIZA FIGUEROA</APELLIDOS>
              <COD_ESTUDIANTE>201262067</COD_ESTUDIANTE>
              <EMAIL>joyapiza@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes3" msdata:rowOrder="2">
              <NOMBRES>LUIS EFREN</NOMBRES>
              <APELLIDOS>HERRERA BAÑOS</APELLIDOS>
              <COD_ESTUDIANTE>201310157</COD_ESTUDIANTE>
              <EMAIL>luefherr@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes4" msdata:rowOrder="3">
              <NOMBRES>HENRY DAVID</NOMBRES>
              <APELLIDOS>PUHUEYESTEWA SARANGO</APELLIDOS>
              <COD_ESTUDIANTE>201311008</COD_ESTUDIANTE>
              <EMAIL>hpuhueye@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes5" msdata:rowOrder="4">
              <NOMBRES>CARLOS ENRIQUE</NOMBRES>
              <APELLIDOS>MORAN CHONANA</APELLIDOS>
              <COD_ESTUDIANTE>201401099</COD_ESTUDIANTE>
              <EMAIL>cemoran@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes6" msdata:rowOrder="5">
              <NOMBRES>AYRTON MODESTO</NOMBRES>
              <APELLIDOS>GUEVARA MURILLO</APELLIDOS>
              <COD_ESTUDIANTE>201401265</COD_ESTUDIANTE>
              <EMAIL>ayrmogue@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes7" msdata:rowOrder="6">
              <NOMBRES>ANGEL EDUARDO</NOMBRES>
              <APELLIDOS>ORTEGA NIETO</APELLIDOS>
              <COD_ESTUDIANTE>201402547</COD_ESTUDIANTE>
              <EMAIL>aeortega@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes8" msdata:rowOrder="7">
              <NOMBRES>MARIA LAURA</NOMBRES>
              <APELLIDOS>ARTEAGA GARCIA</APELLIDOS>
              <COD_ESTUDIANTE>201403998</COD_ESTUDIANTE>
              <EMAIL>malaarte@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes9" msdata:rowOrder="8">
              <NOMBRES>MEGAN SHAMILLOU</NOMBRES>
              <APELLIDOS>ASPIAZU SALAZAR</APELLIDOS>
              <COD_ESTUDIANTE>201411800</COD_ESTUDIANTE>
              <EMAIL>msaspiaz@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes10" msdata:rowOrder="9">
              <NOMBRES>ANGEL JESUS</NOMBRES>
              <APELLIDOS>MOSQUERA VILLA</APELLIDOS>
              <COD_ESTUDIANTE>201412252</COD_ESTUDIANTE>
              <EMAIL>ajmosque@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes11" msdata:rowOrder="10">
              <NOMBRES>DORA PAMELA</NOMBRES>
              <APELLIDOS>CASA  BELTRAN</APELLIDOS>
              <COD_ESTUDIANTE>201412603</COD_ESTUDIANTE>
              <EMAIL>dopacasa@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes12" msdata:rowOrder="11">
              <NOMBRES>KATHERINE YANINA</NOMBRES>
              <APELLIDOS>MORALES TIERRA</APELLIDOS>
              <COD_ESTUDIANTE>201412937</COD_ESTUDIANTE>
              <EMAIL>kymorale@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes13" msdata:rowOrder="12">
              <NOMBRES>WILSON EFRAIN</NOMBRES>
              <APELLIDOS>FRANCO VEINTIMILLA</APELLIDOS>
              <COD_ESTUDIANTE>201416619</COD_ESTUDIANTE>
              <EMAIL>wilefran@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes14" msdata:rowOrder="13">
              <NOMBRES>RAUL ALBERTO</NOMBRES>
              <APELLIDOS>SALAMANCA VILLA</APELLIDOS>
              <COD_ESTUDIANTE>201421085</COD_ESTUDIANTE>
              <EMAIL>rsalaman@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes15" msdata:rowOrder="14">
              <NOMBRES>JENNIFFER MELISSA</NOMBRES>
              <APELLIDOS>GALARZA TITUANA</APELLIDOS>
              <COD_ESTUDIANTE>201450020</COD_ESTUDIANTE>
              <EMAIL>jmgalarz@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes16" msdata:rowOrder="15">
              <NOMBRES>JOHARA ELVIRA</NOMBRES>
              <APELLIDOS>SARMIENTO TAPIA</APELLIDOS>
              <COD_ESTUDIANTE>201501116</COD_ESTUDIANTE>
              <EMAIL>johelsar@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes17" msdata:rowOrder="16">
              <NOMBRES>CRISTHIAN ALEXANDER</NOMBRES>
              <APELLIDOS>AVEIGA REYES</APELLIDOS>
              <COD_ESTUDIANTE>201503124</COD_ESTUDIANTE>
              <EMAIL>caaveiga@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes18" msdata:rowOrder="17">
              <NOMBRES>HAIRO DANILO</NOMBRES>
              <APELLIDOS>VERA DEMERA</APELLIDOS>
              <COD_ESTUDIANTE>201503154</COD_ESTUDIANTE>
              <EMAIL>haidvera@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes19" msdata:rowOrder="18">
              <NOMBRES>ANTHONY DARIO</NOMBRES>
              <APELLIDOS>HERNANDEZ TAMAYO</APELLIDOS>
              <COD_ESTUDIANTE>201504309</COD_ESTUDIANTE>
              <EMAIL>antdhern@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes20" msdata:rowOrder="19">
              <NOMBRES>EDISON JAIR</NOMBRES>
              <APELLIDOS>ALVARADO SARAGUAYO</APELLIDOS>
              <COD_ESTUDIANTE>201504692</COD_ESTUDIANTE>
              <EMAIL>ejalvara@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes21" msdata:rowOrder="20">
              <NOMBRES>DARIEN ESTEBAN</NOMBRES>
              <APELLIDOS>LOPEZ VALDEZ</APELLIDOS>
              <COD_ESTUDIANTE>201505260</COD_ESTUDIANTE>
              <EMAIL>dareslop@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes22" msdata:rowOrder="21">
              <NOMBRES>FANNY GABRIELA</NOMBRES>
              <APELLIDOS>YEPEZ GUAMAN</APELLIDOS>
              <COD_ESTUDIANTE>201505769</COD_ESTUDIANTE>
              <EMAIL>fgyepez@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes23" msdata:rowOrder="22">
              <NOMBRES>BREW JONATHAN</NOMBRES>
              <APELLIDOS>COBOS GRANDA</APELLIDOS>
              <COD_ESTUDIANTE>201505975</COD_ESTUDIANTE>
              <EMAIL>bjcobos@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes24" msdata:rowOrder="23">
              <NOMBRES>MARCELA DENISSE</NOMBRES>
              <APELLIDOS>MUZZIO VILLAFUERTE</APELLIDOS>
              <COD_ESTUDIANTE>201506367</COD_ESTUDIANTE>
              <EMAIL>mmuzzio@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes25" msdata:rowOrder="24">
              <NOMBRES>ALDO FRANCISCO</NOMBRES>
              <APELLIDOS>RODRIGUEZ MENDOZA</APELLIDOS>
              <COD_ESTUDIANTE>201508325</COD_ESTUDIANTE>
              <EMAIL>alfrrodr@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes26" msdata:rowOrder="25">
              <NOMBRES>LUIS XAVIER</NOMBRES>
              <APELLIDOS>GONZALEZ ARREAGA</APELLIDOS>
              <COD_ESTUDIANTE>201508423</COD_ESTUDIANTE>
              <EMAIL>lxgonzal@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes27" msdata:rowOrder="26">
              <NOMBRES>RENATTO CARLO</NOMBRES>
              <APELLIDOS>CENTANARO VEGA</APELLIDOS>
              <COD_ESTUDIANTE>201508824</COD_ESTUDIANTE>
              <EMAIL>rccentan@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes28" msdata:rowOrder="27">
              <NOMBRES>DANIEL AARON</NOMBRES>
              <APELLIDOS>LEONES CONTRERAS</APELLIDOS>
              <COD_ESTUDIANTE>201508854</COD_ESTUDIANTE>
              <EMAIL>daleones@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes29" msdata:rowOrder="28">
              <NOMBRES>JESUS GREGORY</NOMBRES>
              <APELLIDOS>KLINGER LANDAZURI</APELLIDOS>
              <COD_ESTUDIANTE>201509128</COD_ESTUDIANTE>
              <EMAIL>jklinger@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes30" msdata:rowOrder="29">
              <NOMBRES>BELEN STEPHANIE</NOMBRES>
              <APELLIDOS>ACUÑA MERCHAN</APELLIDOS>
              <COD_ESTUDIANTE>201509745</COD_ESTUDIANTE>
              <EMAIL>belstacu@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes31" msdata:rowOrder="30">
              <NOMBRES>GABRIEL MICHAEL</NOMBRES>
              <APELLIDOS>JAIME JAIME</APELLIDOS>
              <COD_ESTUDIANTE>201511653</COD_ESTUDIANTE>
              <EMAIL>mgjaime@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes32" msdata:rowOrder="31">
              <NOMBRES>LIZBETH PATRICIA</NOMBRES>
              <APELLIDOS>CAICEDO BARRERA</APELLIDOS>
              <COD_ESTUDIANTE>201511761</COD_ESTUDIANTE>
              <EMAIL>lizpacai@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes33" msdata:rowOrder="32">
              <NOMBRES>KEVIN EDUARDO</NOMBRES>
              <APELLIDOS>CARRASCO CEVALLOS</APELLIDOS>
              <COD_ESTUDIANTE>201511839</COD_ESTUDIANTE>
              <EMAIL>kcarrasc@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes34" msdata:rowOrder="33">
              <NOMBRES>DARWIN NAGHIT</NOMBRES>
              <APELLIDOS>ARIAS DELGADO</APELLIDOS>
              <COD_ESTUDIANTE>201512584</COD_ESTUDIANTE>
              <EMAIL>dnarias@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes35" msdata:rowOrder="34">
              <NOMBRES>JOHAN</NOMBRES>
              <APELLIDOS>LOOR ROMERO</APELLIDOS>
              <COD_ESTUDIANTE>201514788</COD_ESTUDIANTE>
              <EMAIL>loor@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes36" msdata:rowOrder="35">
              <NOMBRES>KAREN THALIA</NOMBRES>
              <APELLIDOS>PAZMIÑO GARCIA</APELLIDOS>
              <COD_ESTUDIANTE>201514904</COD_ESTUDIANTE>
              <EMAIL>kpazmino@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes37" msdata:rowOrder="36">
              <NOMBRES>JHON JAIRO</NOMBRES>
              <APELLIDOS>ALBERCA MOROCHO</APELLIDOS>
              <COD_ESTUDIANTE>201514954</COD_ESTUDIANTE>
              <EMAIL>jalberca@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes38" msdata:rowOrder="37">
              <NOMBRES>GABRIELA ISABEL</NOMBRES>
              <APELLIDOS>VILLARROEL PROAÑO</APELLIDOS>
              <COD_ESTUDIANTE>201515042</COD_ESTUDIANTE>
              <EMAIL>gvillarr@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes39" msdata:rowOrder="38">
              <NOMBRES>VINICIO JESUS</NOMBRES>
              <APELLIDOS>PERALTA MERELO</APELLIDOS>
              <COD_ESTUDIANTE>201515414</COD_ESTUDIANTE>
              <EMAIL>vperalta@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes40" msdata:rowOrder="39">
              <NOMBRES>BRYAN DARIO</NOMBRES>
              <APELLIDOS>ROSADO VALLEJO</APELLIDOS>
              <COD_ESTUDIANTE>201515669</COD_ESTUDIANTE>
              <EMAIL>brosado@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes41" msdata:rowOrder="40">
              <NOMBRES>DIEGO ALEJANDRO</NOMBRES>
              <APELLIDOS>BELTRAN ZUMBA</APELLIDOS>
              <COD_ESTUDIANTE>201515943</COD_ESTUDIANTE>
              <EMAIL>dialbelt@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes42" msdata:rowOrder="41">
              <NOMBRES>JUAN MATEO</NOMBRES>
              <APELLIDOS>RAMOS DIAZ</APELLIDOS>
              <COD_ESTUDIANTE>201515973</COD_ESTUDIANTE>
              <EMAIL>jmramos@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes43" msdata:rowOrder="42">
              <NOMBRES>LUIS EMILIO</NOMBRES>
              <APELLIDOS>LERQUE CARVAJAL</APELLIDOS>
              <COD_ESTUDIANTE>201516149</COD_ESTUDIANTE>
              <EMAIL>lelerque@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes44" msdata:rowOrder="43">
              <NOMBRES>MIGUEL ANGEL</NOMBRES>
              <APELLIDOS>PASMAY GOMEZ</APELLIDOS>
              <COD_ESTUDIANTE>201516179</COD_ESTUDIANTE>
              <EMAIL>mapasmay@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes45" msdata:rowOrder="44">
              <NOMBRES>DAVID ANDRES</NOMBRES>
              <APELLIDOS>LLERENA AMON</APELLIDOS>
              <COD_ESTUDIANTE>201516962</COD_ESTUDIANTE>
              <EMAIL>dllerena@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes46" msdata:rowOrder="45">
              <NOMBRES>ISIS SOLANGE</NOMBRES>
              <APELLIDOS>QUICHIMBO ARRIAGA</APELLIDOS>
              <COD_ESTUDIANTE>201517226</COD_ESTUDIANTE>
              <EMAIL>issoquic@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes47" msdata:rowOrder="46">
              <NOMBRES>CRISTINA GUADALUPE</NOMBRES>
              <APELLIDOS>SINCHI NACIPUCHA</APELLIDOS>
              <COD_ESTUDIANTE>201600368</COD_ESTUDIANTE>
              <EMAIL>csinchi@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes48" msdata:rowOrder="47">
              <NOMBRES>JOSE FABRICIO</NOMBRES>
              <APELLIDOS>HERRERA CEDEÑO</APELLIDOS>
              <COD_ESTUDIANTE>201601192</COD_ESTUDIANTE>
              <EMAIL>jfherrer@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes49" msdata:rowOrder="48">
              <NOMBRES>LINDTHON ANDRES</NOMBRES>
              <APELLIDOS>IPARREÑO SANTAMARIA</APELLIDOS>
              <COD_ESTUDIANTE>201601226</COD_ESTUDIANTE>
              <EMAIL>liparren@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes50" msdata:rowOrder="49">
              <NOMBRES>CHRISTIAN JESUS</NOMBRES>
              <APELLIDOS>RIVERA TROYA</APELLIDOS>
              <COD_ESTUDIANTE>201601275</COD_ESTUDIANTE>
              <EMAIL>chrjeriv@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes51" msdata:rowOrder="50">
              <NOMBRES>JAIME ALEXANDER</NOMBRES>
              <APELLIDOS>ALARCON ALARCON</APELLIDOS>
              <COD_ESTUDIANTE>201601317</COD_ESTUDIANTE>
              <EMAIL>jaiaalar@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes52" msdata:rowOrder="51">
              <NOMBRES>CARLOS ANDRES</NOMBRES>
              <APELLIDOS>ALVAREZ VIVAR</APELLIDOS>
              <COD_ESTUDIANTE>201601473</COD_ESTUDIANTE>
              <EMAIL>caraalva@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes53" msdata:rowOrder="52">
              <NOMBRES>TAMARA KARINA</NOMBRES>
              <APELLIDOS>GARCIA ROMO</APELLIDOS>
              <COD_ESTUDIANTE>201601630</COD_ESTUDIANTE>
              <EMAIL>tkgarcia@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes54" msdata:rowOrder="53">
              <NOMBRES>JAVIER ANDRES</NOMBRES>
              <APELLIDOS>POLIT BRAVO</APELLIDOS>
              <COD_ESTUDIANTE>201601689</COD_ESTUDIANTE>
              <EMAIL>jpolit@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes55" msdata:rowOrder="54">
              <NOMBRES>JORDAN RONALDO</NOMBRES>
              <APELLIDOS>NIOLA ARMIJOS</APELLIDOS>
              <COD_ESTUDIANTE>201602059</COD_ESTUDIANTE>
              <EMAIL>jrniola@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes56" msdata:rowOrder="55">
              <NOMBRES>KENNETH JOSUE</NOMBRES>
              <APELLIDOS>ALEJANDRO SOLORZANO</APELLIDOS>
              <COD_ESTUDIANTE>201602281</COD_ESTUDIANTE>
              <EMAIL>kenjoale@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes57" msdata:rowOrder="56">
              <NOMBRES>SANDY ARACELY</NOMBRES>
              <APELLIDOS>CRUZ PINCAY</APELLIDOS>
              <COD_ESTUDIANTE>201602307</COD_ESTUDIANTE>
              <EMAIL>sacruz@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes58" msdata:rowOrder="57">
              <NOMBRES>SANDRA ISABELLA</NOMBRES>
              <APELLIDOS>COELLO SUAREZ</APELLIDOS>
              <COD_ESTUDIANTE>201602950</COD_ESTUDIANTE>
              <EMAIL>saiscoel@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes59" msdata:rowOrder="58">
              <NOMBRES>DAVID ALEJANDRO</NOMBRES>
              <APELLIDOS>TORRES TORRES</APELLIDOS>
              <COD_ESTUDIANTE>201602976</COD_ESTUDIANTE>
              <EMAIL>davatorr@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes60" msdata:rowOrder="59">
              <NOMBRES>JOEL RUBEN</NOMBRES>
              <APELLIDOS>MORAN ARMENDARIZ</APELLIDOS>
              <COD_ESTUDIANTE>201603354</COD_ESTUDIANTE>
              <EMAIL>joermora@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes61" msdata:rowOrder="60">
              <NOMBRES>SULLY EDITA</NOMBRES>
              <APELLIDOS>RIVAS CACERES</APELLIDOS>
              <COD_ESTUDIANTE>201603370</COD_ESTUDIANTE>
              <EMAIL>serivas@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes62" msdata:rowOrder="61">
              <NOMBRES>LIZZI BRIGGITTE</NOMBRES>
              <APELLIDOS>GARCIA CASTRO</APELLIDOS>
              <COD_ESTUDIANTE>201603644</COD_ESTUDIANTE>
              <EMAIL>lizbgarc@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes63" msdata:rowOrder="62">
              <NOMBRES>WILMER STEVEN</NOMBRES>
              <APELLIDOS>CHANALATA BRITO</APELLIDOS>
              <COD_ESTUDIANTE>201604568</COD_ESTUDIANTE>
              <EMAIL>wchanala@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes64" msdata:rowOrder="63">
              <NOMBRES>NELSON ARTURO</NOMBRES>
              <APELLIDOS>CASTRO JAIME</APELLIDOS>
              <COD_ESTUDIANTE>201604931</COD_ESTUDIANTE>
              <EMAIL>nearcast@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes65" msdata:rowOrder="64">
              <NOMBRES>MARIO RENE</NOMBRES>
              <APELLIDOS>TOCAGON CABASCANGO</APELLIDOS>
              <COD_ESTUDIANTE>201605821</COD_ESTUDIANTE>
              <EMAIL>marretoc@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes66" msdata:rowOrder="65">
              <NOMBRES>MEI LING</NOMBRES>
              <APELLIDOS>CHANGKUON ARBOLEDA</APELLIDOS>
              <COD_ESTUDIANTE>201606332</COD_ESTUDIANTE>
              <EMAIL>melichan@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes67" msdata:rowOrder="66">
              <NOMBRES>NATHALY CARMEN</NOMBRES>
              <APELLIDOS>BAQUE NAREA</APELLIDOS>
              <COD_ESTUDIANTE>201606886</COD_ESTUDIANTE>
              <EMAIL>ncbaque@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes68" msdata:rowOrder="67">
              <NOMBRES>KEVIN RAFAEL</NOMBRES>
              <APELLIDOS>CAICEDO CARDENAS</APELLIDOS>
              <COD_ESTUDIANTE>201607694</COD_ESTUDIANTE>
              <EMAIL>kevracai@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes69" msdata:rowOrder="68">
              <NOMBRES>LIZBETH NAIDINE</NOMBRES>
              <APELLIDOS>GUILLCA ALVAREZ</APELLIDOS>
              <COD_ESTUDIANTE>201607702</COD_ESTUDIANTE>
              <EMAIL>lguillca@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes70" msdata:rowOrder="69">
              <NOMBRES>DANIELA CAROLINA</NOMBRES>
              <APELLIDOS>STAY AREVALO</APELLIDOS>
              <COD_ESTUDIANTE>201607801</COD_ESTUDIANTE>
              <EMAIL>dcstay@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes71" msdata:rowOrder="70">
              <NOMBRES>JEREMY CARLOS</NOMBRES>
              <APELLIDOS>LEON ANDRADE</APELLIDOS>
              <COD_ESTUDIANTE>201608098</COD_ESTUDIANTE>
              <EMAIL>jercleon@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes72" msdata:rowOrder="71">
              <NOMBRES>YSABEL YAMILETH</NOMBRES>
              <APELLIDOS>ATIENCIA CALLE</APELLIDOS>
              <COD_ESTUDIANTE>201608288</COD_ESTUDIANTE>
              <EMAIL>yatienci@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes73" msdata:rowOrder="72">
              <NOMBRES>GUSTAVO FERNANDO</NOMBRES>
              <APELLIDOS>RUIZ BARROS</APELLIDOS>
              <COD_ESTUDIANTE>201608379</COD_ESTUDIANTE>
              <EMAIL>gfruiz@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes74" msdata:rowOrder="73">
              <NOMBRES>JAIME DANIEL</NOMBRES>
              <APELLIDOS>ZAPATA ORTIZ</APELLIDOS>
              <COD_ESTUDIANTE>201608387</COD_ESTUDIANTE>
              <EMAIL>jdzapata@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes75" msdata:rowOrder="74">
              <NOMBRES>JOSE ANDRES</NOMBRES>
              <APELLIDOS>VILLAGOMEZ ARBOLEDA</APELLIDOS>
              <COD_ESTUDIANTE>201608395</COD_ESTUDIANTE>
              <EMAIL>josanvil@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes76" msdata:rowOrder="75">
              <NOMBRES>RAMIRO STALIN</NOMBRES>
              <APELLIDOS>SUCO SAN LUCAS</APELLIDOS>
              <COD_ESTUDIANTE>201608429</COD_ESTUDIANTE>
              <EMAIL>ramssuco@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes77" msdata:rowOrder="76">
              <NOMBRES>ABRAHAM JOSE</NOMBRES>
              <APELLIDOS>SANDOYA LARA</APELLIDOS>
              <COD_ESTUDIANTE>201608478</COD_ESTUDIANTE>
              <EMAIL>abjosand@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes78" msdata:rowOrder="77">
              <NOMBRES>ALEJANDRO JAVIER</NOMBRES>
              <APELLIDOS>TORRES NARANJO</APELLIDOS>
              <COD_ESTUDIANTE>201608502</COD_ESTUDIANTE>
              <EMAIL>ajtorres@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes79" msdata:rowOrder="78">
              <NOMBRES>GABRIEL ESTEVEN</NOMBRES>
              <APELLIDOS>MORAN CHOEZ</APELLIDOS>
              <COD_ESTUDIANTE>201608544</COD_ESTUDIANTE>
              <EMAIL>gemoran@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes80" msdata:rowOrder="79">
              <NOMBRES>PABLO ANDRES</NOMBRES>
              <APELLIDOS>GORDILLO SILVA</APELLIDOS>
              <COD_ESTUDIANTE>201608593</COD_ESTUDIANTE>
              <EMAIL>pagordil@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes81" msdata:rowOrder="80">
              <NOMBRES>DANNY ALEJANDRO</NOMBRES>
              <APELLIDOS>VASQUEZ MOREIRA</APELLIDOS>
              <COD_ESTUDIANTE>201608684</COD_ESTUDIANTE>
              <EMAIL>daalvasq@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes82" msdata:rowOrder="81">
              <NOMBRES>JORDY AUGUSTO</NOMBRES>
              <APELLIDOS>MORALES MOREIRA</APELLIDOS>
              <COD_ESTUDIANTE>201608726</COD_ESTUDIANTE>
              <EMAIL>joaumora@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes83" msdata:rowOrder="82">
              <NOMBRES>PATRICIA ALEJANDRA</NOMBRES>
              <APELLIDOS>ANDRADE HUERTA</APELLIDOS>
              <COD_ESTUDIANTE>201608767</COD_ESTUDIANTE>
              <EMAIL>pataland@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes84" msdata:rowOrder="83">
              <NOMBRES>JOHN FREDDY</NOMBRES>
              <APELLIDOS>MORA PICO</APELLIDOS>
              <COD_ESTUDIANTE>201608874</COD_ESTUDIANTE>
              <EMAIL>jofrmora@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes85" msdata:rowOrder="84">
              <NOMBRES>DANIELA DE FATIMA</NOMBRES>
              <APELLIDOS>RIVAS PASTOR</APELLIDOS>
              <COD_ESTUDIANTE>201608957</COD_ESTUDIANTE>
              <EMAIL>drivas@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes86" msdata:rowOrder="85">
              <NOMBRES>FREDDY ARTURO</NOMBRES>
              <APELLIDOS>PALADINES LARCO</APELLIDOS>
              <COD_ESTUDIANTE>201608965</COD_ESTUDIANTE>
              <EMAIL>frearpal@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes87" msdata:rowOrder="86">
              <NOMBRES>JHOSTIN GIUSEP</NOMBRES>
              <APELLIDOS>OCAMPO VELEZ</APELLIDOS>
              <COD_ESTUDIANTE>201609070</COD_ESTUDIANTE>
              <EMAIL>jgocampo@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes88" msdata:rowOrder="87">
              <NOMBRES>LUIS ADRIAN</NOMBRES>
              <APELLIDOS>ZAMORA VELIZ</APELLIDOS>
              <COD_ESTUDIANTE>201609104</COD_ESTUDIANTE>
              <EMAIL>lzamora@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes89" msdata:rowOrder="88">
              <NOMBRES>MONSERRAT ISABEL</NOMBRES>
              <APELLIDOS>CORDERO PINARGOTE</APELLIDOS>
              <COD_ESTUDIANTE>201609294</COD_ESTUDIANTE>
              <EMAIL>monicord@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes90" msdata:rowOrder="89">
              <NOMBRES>LUIS ORLANDO</NOMBRES>
              <APELLIDOS>ARMIJOS CEVALLOS</APELLIDOS>
              <COD_ESTUDIANTE>201609369</COD_ESTUDIANTE>
              <EMAIL>loarmijo@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes91" msdata:rowOrder="90">
              <NOMBRES>MARIA JOSE</NOMBRES>
              <APELLIDOS>NOVILLO COELLO</APELLIDOS>
              <COD_ESTUDIANTE>201609492</COD_ESTUDIANTE>
              <EMAIL>majonovi@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes92" msdata:rowOrder="91">
              <NOMBRES>SERGIO LEONARDO</NOMBRES>
              <APELLIDOS>RAMOS BAYAS</APELLIDOS>
              <COD_ESTUDIANTE>201609518</COD_ESTUDIANTE>
              <EMAIL>serleram@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes93" msdata:rowOrder="92">
              <NOMBRES>FRANKLIN SEBASTIAN</NOMBRES>
              <APELLIDOS>GARCIA ZAMBRANO</APELLIDOS>
              <COD_ESTUDIANTE>201609534</COD_ESTUDIANTE>
              <EMAIL>fsgarcia@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes94" msdata:rowOrder="93">
              <NOMBRES>JANCARLO ANDRE</NOMBRES>
              <APELLIDOS>VALENCIA NOBOA</APELLIDOS>
              <COD_ESTUDIANTE>201609559</COD_ESTUDIANTE>
              <EMAIL>jananval@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes95" msdata:rowOrder="94">
              <NOMBRES>NICOLE ANDREA</NOMBRES>
              <APELLIDOS>ERAZO WELLINGTON</APELLIDOS>
              <COD_ESTUDIANTE>201609625</COD_ESTUDIANTE>
              <EMAIL>naerazo@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes96" msdata:rowOrder="95">
              <NOMBRES>PABLO ANTHONY</NOMBRES>
              <APELLIDOS>VILLA ALVAREZ</APELLIDOS>
              <COD_ESTUDIANTE>201609633</COD_ESTUDIANTE>
              <EMAIL>pavilla@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes97" msdata:rowOrder="96">
              <NOMBRES>CESAR ANTONIO</NOMBRES>
              <APELLIDOS>COLOMA GUZMAN</APELLIDOS>
              <COD_ESTUDIANTE>201609807</COD_ESTUDIANTE>
              <EMAIL>ccoloma@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes98" msdata:rowOrder="97">
              <NOMBRES>ANDREA GABRIELA</NOMBRES>
              <APELLIDOS>HARO FIALLOS</APELLIDOS>
              <COD_ESTUDIANTE>201611167</COD_ESTUDIANTE>
              <EMAIL>agharo@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes99" msdata:rowOrder="98">
              <NOMBRES>KAREN ANDREA</NOMBRES>
              <APELLIDOS>RIVAS ZAMBRANO</APELLIDOS>
              <COD_ESTUDIANTE>201611183</COD_ESTUDIANTE>
              <EMAIL>karivas@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes100" msdata:rowOrder="99">
              <NOMBRES>MARIA BEATRIZ</NOMBRES>
              <APELLIDOS>BARCIA CARREÑO</APELLIDOS>
              <COD_ESTUDIANTE>201611316</COD_ESTUDIANTE>
              <EMAIL>mbbarcia@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes101" msdata:rowOrder="100">
              <NOMBRES>RENATA NAOMI</NOMBRES>
              <APELLIDOS>NAVIA GILER</APELLIDOS>
              <COD_ESTUDIANTE>201611332</COD_ESTUDIANTE>
              <EMAIL>rnavia@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes102" msdata:rowOrder="101">
              <NOMBRES>GABRIEL RICARDO</NOMBRES>
              <APELLIDOS>VELASQUEZ ALBUJA</APELLIDOS>
              <COD_ESTUDIANTE>201612017</COD_ESTUDIANTE>
              <EMAIL>gabrivel@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes103" msdata:rowOrder="102">
              <NOMBRES>ANDRES STEVEN</NOMBRES>
              <APELLIDOS>FLORES MARTINEZ</APELLIDOS>
              <COD_ESTUDIANTE>201612090</COD_ESTUDIANTE>
              <EMAIL>ansteflo@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes104" msdata:rowOrder="103">
              <NOMBRES>LEOPOLDO ANIBAL</NOMBRES>
              <APELLIDOS>MANCHENO POVEDA</APELLIDOS>
              <COD_ESTUDIANTE>201612280</COD_ESTUDIANTE>
              <EMAIL>lamanche@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes105" msdata:rowOrder="104">
              <NOMBRES>NICOLAS MIGUEL</NOMBRES>
              <APELLIDOS>TORRES ORTEGA</APELLIDOS>
              <COD_ESTUDIANTE>201612298</COD_ESTUDIANTE>
              <EMAIL>nmtorres@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes106" msdata:rowOrder="105">
              <NOMBRES>OSCAR SEBASTIAN</NOMBRES>
              <APELLIDOS>FLORES GUERRERO</APELLIDOS>
              <COD_ESTUDIANTE>201612306</COD_ESTUDIANTE>
              <EMAIL>osflores@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes107" msdata:rowOrder="106">
              <NOMBRES>WASHINGTON FABIAN</NOMBRES>
              <APELLIDOS>MUÑOZ ZUÑIGA</APELLIDOS>
              <COD_ESTUDIANTE>201612348</COD_ESTUDIANTE>
              <EMAIL>wfmunoz@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes108" msdata:rowOrder="107">
              <NOMBRES>DUVAL JOEL</NOMBRES>
              <APELLIDOS>JARAMILLO PORRAS</APELLIDOS>
              <COD_ESTUDIANTE>201612694</COD_ESTUDIANTE>
              <EMAIL>duvjojar@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes109" msdata:rowOrder="108">
              <NOMBRES>EDUARDO HUMBERTO</NOMBRES>
              <APELLIDOS>TUMBACO ROCAFUERTE</APELLIDOS>
              <COD_ESTUDIANTE>201612967</COD_ESTUDIANTE>
              <EMAIL>ehtumbac@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes110" msdata:rowOrder="109">
              <NOMBRES>ROBERTO HERNAN</NOMBRES>
              <APELLIDOS>AQUINO ZAMBRANO</APELLIDOS>
              <COD_ESTUDIANTE>201613148</COD_ESTUDIANTE>
              <EMAIL>robhaqui@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes111" msdata:rowOrder="110">
              <NOMBRES>GALO XAVIER</NOMBRES>
              <APELLIDOS>FIGUEROA VILLACRESES</APELLIDOS>
              <COD_ESTUDIANTE>201613528</COD_ESTUDIANTE>
              <EMAIL>gxfiguer@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes112" msdata:rowOrder="111">
              <NOMBRES>SOFIA EDELMIRA</NOMBRES>
              <APELLIDOS>TENORIO FABARA</APELLIDOS>
              <COD_ESTUDIANTE>201613825</COD_ESTUDIANTE>
              <EMAIL>stenorio@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes113" msdata:rowOrder="112">
              <NOMBRES>MARIA VICTORIA</NOMBRES>
              <APELLIDOS>ORTEGA ANDRADE</APELLIDOS>
              <COD_ESTUDIANTE>201614229</COD_ESTUDIANTE>
              <EMAIL>mvortega@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes114" msdata:rowOrder="113">
              <NOMBRES>DIEGO ANDRES</NOMBRES>
              <APELLIDOS>YANCE ALVAREZ</APELLIDOS>
              <COD_ESTUDIANTE>201614245</COD_ESTUDIANTE>
              <EMAIL>dyance@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes115" msdata:rowOrder="114">
              <NOMBRES>CARLOS LUIS</NOMBRES>
              <APELLIDOS>ESPINOZA MOLINA</APELLIDOS>
              <COD_ESTUDIANTE>201614278</COD_ESTUDIANTE>
              <EMAIL>carlespi@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes116" msdata:rowOrder="115">
              <NOMBRES>JOSUE OSWALDO</NOMBRES>
              <APELLIDOS>CONTRERAS BARZOLA</APELLIDOS>
              <COD_ESTUDIANTE>201614468</COD_ESTUDIANTE>
              <EMAIL>jocontre@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes117" msdata:rowOrder="116">
              <NOMBRES>XIOMARA ELIZABETH</NOMBRES>
              <APELLIDOS>MONCERRATE MALDONADO</APELLIDOS>
              <COD_ESTUDIANTE>201614518</COD_ESTUDIANTE>
              <EMAIL>xielmonc@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
            <Estudiantes diffgr:id="Estudiantes118" msdata:rowOrder="117">
              <NOMBRES>LUIS FERNANDO</NOMBRES>
              <APELLIDOS>LALANGUI PULLA</APELLIDOS>
              <COD_ESTUDIANTE>201614914</COD_ESTUDIANTE>
              <EMAIL>lufelala@espol.edu.ec</EMAIL>
              <PARALELO>1  </PARALELO>
              <COD_MATERIA_ACAD>FISG1002  </COD_MATERIA_ACAD>
              <NOMBRE>FÍSICA II</NOMBRE>
            </Estudiantes>
          </NewDataSet>
        </diffgr:diffgram>
      </wsConsultaEstudiantesResult>
    </wsConsultaEstudiantesResponse>
  </soap:Body>
</soap:Envelope>
